# Calico Version v3.0.2
# https://docs.projectcalico.org/v3.0/releases#v3.0.2
# This manifest includes the following component versions:
#   calico/ctl:v2.0.0

apiVersion: v1
kind: Pod
metadata:
  name: calicoctl
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: calicoctl
    # image: quay.io/calico/ctl:v2.0.0
    image: devops-reg.io/k8s/ctl:v2.0.0
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    env:
    - name: ETCD_ENDPOINTS
      valueFrom:
        configMapKeyRef:
          name: calico-config
          key: etcd_endpoints
